{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "2eb1f1d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "a5f7039e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>eventid</th>\n",
       "      <th>iyear</th>\n",
       "      <th>imonth</th>\n",
       "      <th>iday</th>\n",
       "      <th>approxdate</th>\n",
       "      <th>extended</th>\n",
       "      <th>resolution</th>\n",
       "      <th>country</th>\n",
       "      <th>country_txt</th>\n",
       "      <th>region</th>\n",
       "      <th>...</th>\n",
       "      <th>addnotes</th>\n",
       "      <th>scite1</th>\n",
       "      <th>scite2</th>\n",
       "      <th>scite3</th>\n",
       "      <th>dbsource</th>\n",
       "      <th>INT_LOG</th>\n",
       "      <th>INT_IDEO</th>\n",
       "      <th>INT_MISC</th>\n",
       "      <th>INT_ANY</th>\n",
       "      <th>related</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>202101010004</td>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaT</td>\n",
       "      <td>60</td>\n",
       "      <td>Egypt</td>\n",
       "      <td>10</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>\"Egyptian officials: Roadside bombing in Sinai...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>START Primary Collection</td>\n",
       "      <td>-9</td>\n",
       "      <td>-9</td>\n",
       "      <td>0</td>\n",
       "      <td>-9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>202101010005</td>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>01/01/2021</td>\n",
       "      <td>0</td>\n",
       "      <td>NaT</td>\n",
       "      <td>92</td>\n",
       "      <td>India</td>\n",
       "      <td>6</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>\"Terror module busted, seven arrested in J&amp;K,\"...</td>\n",
       "      <td>\"Militants throw grenade on CRPF,\" HT Syndicat...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>START Primary Collection</td>\n",
       "      <td>-9</td>\n",
       "      <td>-9</td>\n",
       "      <td>0</td>\n",
       "      <td>-9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>202101010006</td>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaT</td>\n",
       "      <td>228</td>\n",
       "      <td>Yemen</td>\n",
       "      <td>10</td>\n",
       "      <td>...</td>\n",
       "      <td>There is doubt that this incident meets terror...</td>\n",
       "      <td>\"Civilian reportedly dies of injuries from Hou...</td>\n",
       "      <td>\"UN troubled by civilian deaths in Yemen's Hud...</td>\n",
       "      <td>\"Five women killed in Yemen wedding attack,\" G...</td>\n",
       "      <td>START Primary Collection</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>202101010009</td>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaT</td>\n",
       "      <td>4</td>\n",
       "      <td>Afghanistan</td>\n",
       "      <td>6</td>\n",
       "      <td>...</td>\n",
       "      <td>There is doubt that this incident meets terror...</td>\n",
       "      <td>\"Afghanistan- Ghor Provincial Council Member K...</td>\n",
       "      <td>\"Journalist killed on 1st day of new year in A...</td>\n",
       "      <td>\"Afghanistan: 2021 Begins with Assassination o...</td>\n",
       "      <td>START Primary Collection</td>\n",
       "      <td>-9</td>\n",
       "      <td>-9</td>\n",
       "      <td>0</td>\n",
       "      <td>-9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>202101010024</td>\n",
       "      <td>2021</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaT</td>\n",
       "      <td>182</td>\n",
       "      <td>Somalia</td>\n",
       "      <td>11</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>\"Jubbaland lawmaker killed in car bomb blast,\"...</td>\n",
       "      <td>\"Somali lawmaker killed in a sticky bomb attac...</td>\n",
       "      <td>\"Al-Shabab claims killing regional MP in south...</td>\n",
       "      <td>START Primary Collection</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 135 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        eventid  iyear  imonth  iday  approxdate  extended resolution  \\\n",
       "0  202101010004   2021       1     1         NaN         0        NaT   \n",
       "1  202101010005   2021       1     1  01/01/2021         0        NaT   \n",
       "2  202101010006   2021       1     1         NaN         0        NaT   \n",
       "3  202101010009   2021       1     1         NaN         0        NaT   \n",
       "4  202101010024   2021       1     2         NaN         0        NaT   \n",
       "\n",
       "   country  country_txt  region  ...  \\\n",
       "0       60        Egypt      10  ...   \n",
       "1       92        India       6  ...   \n",
       "2      228        Yemen      10  ...   \n",
       "3        4  Afghanistan       6  ...   \n",
       "4      182      Somalia      11  ...   \n",
       "\n",
       "                                            addnotes  \\\n",
       "0                                                NaN   \n",
       "1                                                NaN   \n",
       "2  There is doubt that this incident meets terror...   \n",
       "3  There is doubt that this incident meets terror...   \n",
       "4                                                NaN   \n",
       "\n",
       "                                              scite1  \\\n",
       "0  \"Egyptian officials: Roadside bombing in Sinai...   \n",
       "1  \"Terror module busted, seven arrested in J&K,\"...   \n",
       "2  \"Civilian reportedly dies of injuries from Hou...   \n",
       "3  \"Afghanistan- Ghor Provincial Council Member K...   \n",
       "4  \"Jubbaland lawmaker killed in car bomb blast,\"...   \n",
       "\n",
       "                                              scite2  \\\n",
       "0                                                NaN   \n",
       "1  \"Militants throw grenade on CRPF,\" HT Syndicat...   \n",
       "2  \"UN troubled by civilian deaths in Yemen's Hud...   \n",
       "3  \"Journalist killed on 1st day of new year in A...   \n",
       "4  \"Somali lawmaker killed in a sticky bomb attac...   \n",
       "\n",
       "                                              scite3  \\\n",
       "0                                                NaN   \n",
       "1                                                NaN   \n",
       "2  \"Five women killed in Yemen wedding attack,\" G...   \n",
       "3  \"Afghanistan: 2021 Begins with Assassination o...   \n",
       "4  \"Al-Shabab claims killing regional MP in south...   \n",
       "\n",
       "                   dbsource  INT_LOG  INT_IDEO INT_MISC INT_ANY  related  \n",
       "0  START Primary Collection       -9        -9        0      -9      NaN  \n",
       "1  START Primary Collection       -9        -9        0      -9      NaN  \n",
       "2  START Primary Collection        0         0        0       0      NaN  \n",
       "3  START Primary Collection       -9        -9        0      -9      NaN  \n",
       "4  START Primary Collection        0         0        0       0      NaN  \n",
       "\n",
       "[5 rows x 135 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_recent_full = pd.read_excel('C:/Users/nates/OneDrive/BYUI-NateHP/DATA PROJECTS/Projects/Upcoming Projects/sahel_terrorism/data/globalterrorismdb_2021Jan-June_1222dist.xlsx')\n",
    "df_recent_full.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a085ba45",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_full = pd.read_excel('C:/Users/nates/OneDrive/BYUI-NateHP/DATA PROJECTS/Projects/Upcoming Projects/sahel_terrorism/data/globalterrorismdb_0522dist (1).xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14144d0f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',\n",
       "       'resolution', 'country', 'country_txt', 'region',\n",
       "       ...\n",
       "       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',\n",
       "       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],\n",
       "      dtype='object', length=135)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new = df_full[df_full['country_txt'].isin(['Mali', 'Niger', 'Burkina Faso'])]\n",
    "recent_new = df_recent_full[df_recent_full['country_txt'].isin(['Mali', 'Niger', 'Burkina Faso'])]\n",
    "\n",
    "new.columns\n",
    "recent_new.columns\n",
    "\n",
    "new.head()\n",
    "recent_new.head()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
